"""pb 动画默认与组帧 — 公共 API 聚合（实现已拆分至子模块）。"""

from bot_server.pb.face_bundle import (
    default_pb_face_bundle,
    demo_pb_face_bundle,
    ensure_pb_face_bundle_shape,
    hot_reload_pb_face_bundle_file,
    load_pb_face_bundle_file,
    load_pb_face_bundle_json_document,
    merge_pb_face_bundle,
    resolve_pb_face_bundle,
)
from bot_server.pb.phoneme_anim import phoneme_seq_to_anim_seq
from bot_server.pb.shapes import (
    PB_ACTION_APPEND,
    PB_ACTION_OPPORTUNISTIC,
    PB_ACTION_REPLACE,
    apply_offset_to_primitives,
    collapse_eye_part,
    collapse_mouth_by_phoneme,
    collapse_nose_part,
    default_face_circles,
    default_mouth_by_phoneme,
    default_mouth_rect_for_phoneme,
    enumerate_zh_phonemes,
    expand_eye_part,
    expand_extra_part,
    expand_mouth_by_phoneme,
    expand_nose_part,
    is_eye_elements_group_entry,
    is_extra_elements_group_entry,
    is_mouth_phoneme_group_entry,
    is_nose_elements_group_entry,
    normalize_primitive_shape,
)
from bot_server.pb.servo_pcm import (
    align_pcm_s16le_mono_to_chunk_ms,
    apply_llm_pb_servo_actions,
    apply_parallel_pb_servo,
    apply_random_pb_servo_actions,
    interleave_tts_phoneme_segs_with_servo_plan,
    pb_json_messages,
)

__all__ = [
    "PB_ACTION_APPEND",
    "PB_ACTION_OPPORTUNISTIC",
    "PB_ACTION_REPLACE",
    "align_pcm_s16le_mono_to_chunk_ms",
    "apply_llm_pb_servo_actions",
    "apply_offset_to_primitives",
    "apply_parallel_pb_servo",
    "apply_random_pb_servo_actions",
    "collapse_eye_part",
    "collapse_mouth_by_phoneme",
    "collapse_nose_part",
    "default_face_circles",
    "default_mouth_by_phoneme",
    "default_mouth_rect_for_phoneme",
    "default_pb_face_bundle",
    "demo_pb_face_bundle",
    "ensure_pb_face_bundle_shape",
    "enumerate_zh_phonemes",
    "expand_eye_part",
    "expand_extra_part",
    "expand_mouth_by_phoneme",
    "expand_nose_part",
    "hot_reload_pb_face_bundle_file",
    "interleave_tts_phoneme_segs_with_servo_plan",
    "is_eye_elements_group_entry",
    "is_extra_elements_group_entry",
    "is_mouth_phoneme_group_entry",
    "is_nose_elements_group_entry",
    "load_pb_face_bundle_file",
    "load_pb_face_bundle_json_document",
    "merge_pb_face_bundle",
    "normalize_primitive_shape",
    "pb_json_messages",
    "phoneme_seq_to_anim_seq",
    "resolve_pb_face_bundle",
]
